// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RH.Models;

namespace RH.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220324030321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RH.Models.Candidato", b =>
                {
                    b.Property<int>("id_candidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cedula")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("departamento_id")
                        .HasColumnType("int");

                    b.Property<string>("experiencia_laboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("principales_capacitaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("principales_competencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("puesto_id")
                        .HasColumnType("int");

                    b.Property<string>("recomendado_por")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary_aspire")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_candidato");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("RH.Models.Capacitaciones", b =>
                {
                    b.Property<int>("id_capacitaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Level_grade_id")
                        .HasColumnType("int");

                    b.Property<int>("date_from")
                        .HasColumnType("int");

                    b.Property<int>("date_to")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("institution")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_capacitaciones");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("RH.Models.Competencias", b =>
                {
                    b.Property<int>("id_competencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion_competencias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_competencias");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("RH.Models.Departamento", b =>
                {
                    b.Property<int>("id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_departamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("RH.Models.Empleado", b =>
                {
                    b.Property<int>("id_empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cedula")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("date_ingreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("monthly_salary")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("puesto_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_empleado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("RH.Models.Experiencia_laboral", b =>
                {
                    b.Property<int>("id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("date_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_candidato")
                        .HasColumnType("int");

                    b.Property<string>("puesto_ocupado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_departamento");

                    b.ToTable("Experiencia_laboral");
                });

            modelBuilder.Entity("RH.Models.Idiomas", b =>
                {
                    b.Property<int>("id_idioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_idioma");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("RH.Models.Level_grade", b =>
                {
                    b.Property<int>("id_level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_level");

                    b.ToTable("Level_grade");
                });

            modelBuilder.Entity("RH.Models.Puesto", b =>
                {
                    b.Property<int>("id_puesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("maximun_salary")
                        .HasColumnType("float");

                    b.Property<double>("minimum_salary")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("risk_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id_puesto");

                    b.ToTable("Puesto");
                });
#pragma warning restore 612, 618
        }
    }
}
